### ISSUE TITLE
Dispatch to ps2homebrew organization

### ISSUE THREAD

**Issue by AKuHAK** [ps2dev/ps2dev#9]
Is it possible to create dispatch actions to the [ps2hombrew ](https://github.com/ps2homebrew) projects? So each project compiles when this docker image is updated. Something like this
```yaml
    strategy:
      matrix:
        repo: ['ps2homebrew/wLaunchELF', 'ps2homebrew/Open-PS2-Loader', 'ps2homebrew/repo3']
    runs-on: ubuntu-latest
    - name: Repository Dispatch to ps2homebrew organization
      uses: peter-evans/repository-dispatch@v1
      with:
        repository: ${{ matrix.repo }}
        token: ${{ secrets.DISPATCH_TOKEN }}
        event-type: ${{ env.NEW_DISPATCH_ACTION }}
        client-payload: '{"ref": "${{ github.ref }}"}'
```
